server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false

spring:
  datasource:
    deiver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgre:5432/postgres
    jdbc-url: jdbc:postgresql://postgre:5432/postgres
    platform: postgres
    username: pgapp
    password: asdfasdf11
    data:
      name: student-datasource
      hikari:
        url: jdbc:postgresql://postgre:5432/postgres
        connection-timeout: 30000
        maximum-pool-size: 10
        minimum-idle: 5
        auto-commit: false
        driver-class-name: org.postgresql.Driver
        username: pgapp
        password: asdfasdf11
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    generate-ddl: true
